version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    working_directory: ~/project/UI-test
    steps:
      - checkout
      - run:
          name: Give execute permissions to node_modules/.bin/*
          command: |
            chmod +x ./node_modules/.bin/nightwatch
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run UI tests
          command: npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

      - run:
          name: Install UI test dependencies
          command: |
            cd UI-test
            npm install
      - run:
          name: Run UI tests
          command: |
            cd UI-test
            npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
