version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    working_directory: ~/project/UI-test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd UI-test
            npm install
      - run:
          name: Run Nightwatch UI Tests on Chrome
          command: |
            npm run test:ui
      - run:
          name: Run additional tests
          command: |
            npm run test:additional
      - run:
          name: Run Nightwatch UI Tests on Chrome
          command: |
            npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

workflows:
  version: 2
  test-ui-only:
    jobs:
      - run-ui-tests
