jobs:
  run-ui-tests:
    executor: node-executor
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd UI-test
            npm install
      - run:
          name: Run tests
          command: |
            cd UI-test
            npm run test:ui
