version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17-browsers

jobs:
  run-ui-tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install UI test dependencies
          command: |
            cd UI-test
            ls -la      # للتأكد إن الملف موجود فعلاً
            cat package.json  # تطبعه كمان لو عايز
            npm install
      - run:
          name: Run UI tests
          command: |
            cd UI-test
            npm run test:ui
      - store_artifacts:
          path: UI-test/tests_output
          destination: ui-test-report

workflows:
  version: 2
  run-tests:
    jobs:
      - run-ui-tests
